Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-12, with the labels that each got.

#107 Change the createFromDbData method to reflect the database data
  src/Recurrence/Aggregates/ProductSubscription.php
  src/Recurrence/Factories/ProductSubscriptionFactory.php
  tests/Recurrence/Factories/ProductSubscriptionFactoryTest.php
Labels: :bug: Bug, :ok_hand: Ready

#106 Create subscription invoice to customer
  src/Recurrence/Factories/ChargeFactory.php
  src/Recurrence/Repositories/ChargeRepository.php
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Recurrence/Repositories/SubscriptionRepository.php
  src/Recurrence/Services/RecurrenceService.php
Labels: :construction: In construction, :sparkles: Feature

#108 Create recurrence tests
  .gitignore
  composer.json
  src/Recurrence/Aggregates/Plan.php
  src/Recurrence/Factories/PlanFactory.php
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Recurrence/Repositories/RepetitionRepository.php
  tests/Abstractions/AbstractRepositoryTest.php
  tests/Recurrence/Aggregates/PlanTests.php
  tests/Recurrence/Aggregates/SubProductTests.php
  tests/Recurrence/Factories/PlanTests.php
  tests/Recurrence/Factories/ProductSubscriptionFactoryTest.php
  tests/Recurrence/Factories/SubProductTest.php
  tests/Recurrence/Repositories/ProductSubscriptionRepositoryTest.php
  tests/Recurrence/Repositories/RepetitionRepositoryTest.php
  tests/Recurrence/ValueObjects/IntervalValueObjectTest.php
  tests/Recurrence/ValueObjects/PricingSchemeValueObjectTest.php
  tests/mock/Concrete/Migrate.php
  tests/mock/Concrete/PlatformCoreSetup.php
  tests/mock/Concrete/PlatformDatabaseDecorator.php
Labels: :ok_hand: Ready

#109 Feature mod 857 create cart conflict recurrence
  src/Recurrence/Aggregates/ProductSubscription.php
  src/Recurrence/Aggregates/Repetition.php
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Recurrence/Repositories/SubProductRepository.php
  src/Recurrence/Repositories/SubscriptionRepository.php
  src/Recurrence/Services/RepetitionService.php
  src/Recurrence/Services/RulesCheckoutService.php
Labels: :sparkles: Feature

#110 Fix a cycles bug on repository
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Recurrence/Services/ProductSubscriptionService.php
Labels: :bug: Bug, :ok_hand: Ready, :sparkles: Enhancement

#113 Fix bug when there is a recursive create operation
  src/Kernel/Abstractions/AbstractRepository.php
Labels: :ambulance: Hotfix, :ok_hand: Ready

#112 Create dictionary subscription cycle
  src/Kernel/Abstractions/AbstractPlatformOrderDecorator.php
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Interfaces/SensibleDataInterface.php
  src/Kernel/Services/APIService.php
  src/Kernel/Services/OrderService.php
  src/Kernel/ValueObjects/AbstractValidString.php
  src/Kernel/ValueObjects/Key/PublicKey.php
  src/Kernel/ValueObjects/PaymentMethod.php
  src/Kernel/ValueObjects/SubscriptionStatus.php
  src/Maintenance/Assets/integrityData
  src/Payment/Aggregates/Item.php
  src/Payment/Aggregates/Order.php
  src/Recurrence/Aggregates/SubProduct.php
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Interfaces/SubscriptionInterface.php
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Recurrence/Repositories/SubscriptionRepository.php
  src/Recurrence/Services/SubscriptionService.php
  tests/mock/Concrete/PlatformCoreSetup.php
Labels: :sparkles: Enhancement, :sparkles: Feature

#115 Fix bug on recurrence products duplicated
  src/Recurrence/Services/ProductSubscriptionService.php
Labels: :bug: Bug, :ok_hand: Ready

#116 Create tests to cover some services
  tests/Recurrence/Aggregates/ProductSubscriptionTest.php
  tests/Recurrence/Aggregates/RepetitionTest.php
  tests/Recurrence/Aggregates/SubProductTests.php
  tests/Recurrence/Services/ProductSubscriptionServiceTest.php
  tests/Recurrence/Services/RulesCheckoutServiceTest.php
Labels: :ok_hand: Ready, :sparkles: Enhancement

#114 Create update and delete plan service
  src/Recurrence/Aggregates/Plan.php
  src/Recurrence/Factories/PlanFactory.php
  src/Recurrence/Repositories/PlanRepository.php
  src/Recurrence/Services/PlanService.php
  tests/Recurrence/Factories/PlanTests.php
Labels: :bug: Bug, :ok_hand: Ready

#117 Fix some bugs on recurrence webhooks
  src/Kernel/Services/APIService.php
  src/Recurrence/Aggregates/Charge.php
  src/Recurrence/Factories/ChargeFactory.php
  src/Recurrence/Repositories/ChargeRepository.php
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Webhook/Services/ChargeRecurrenceService.php
Labels: :bug: Bug, :ok_hand: Ready
