Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-02, with the labels that each got.

#16 Handle webhook order.payment_failed
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Webhook/Exceptions/WebhookAlreadyHandledException.php
  src/Webhook/Exceptions/WebhookHandlerNotFoundException.php
  src/Webhook/Services/OrderHandlerService.php
Labels: Ready, bug, feature

#18 Show installments by configured minimum value
  src/Kernel/Services/InstallmentService.php
  src/Kernel/ValueObjects/Installment.php
Labels: Ready, bug

#20 Add Maintenance and Hub services
  integrityDeploy.php
  src/Hub/Aggregates/InstallToken.php
  src/Hub/Commands/AbstractCommand.php
  src/Hub/Commands/CommandType.php
  src/Hub/Commands/InstallCommand.php
  src/Hub/Commands/UninstallCommand.php
  src/Hub/Commands/UpdateCommand.php
  src/Hub/Factories/HubCommandFactory.php
  src/Hub/Factories/InstallTokenFactory.php
  src/Hub/Repositories/InstallTokenRepository.php
  src/Hub/Services/HubIntegrationService.php
  src/Hub/ValueObjects/HubInstallToken.php
  src/Kernel/Abstractions/AbstractDatabaseDecorator.php
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
  src/Kernel/Aggregates/Charge.php
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Aggregates/Transaction.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Factories/TransactionFactory.php
  src/Kernel/Interfaces/PlatformOrderInterface.php
  src/Kernel/Services/InstallmentService.php
  src/Kernel/Services/LogService.php
  src/Kernel/Services/VersionService.php
  src/Kernel/ValueObjects/Id/AccountId.php
  src/Kernel/ValueObjects/Id/MerchantId.php
  src/Kernel/ValueObjects/Key/AbstractPublicKey.php
  src/Kernel/ValueObjects/Key/AbstractSecretKey.php
  src/Kernel/ValueObjects/Key/HubAccessTokenKey.php
  src/Kernel/ValueObjects/Key/PublicKey.php
  src/Kernel/ValueObjects/Key/SecretKey.php
  src/Kernel/ValueObjects/Key/TestPublicKey.php
  src/Kernel/ValueObjects/Key/TestSecretKey.php
  src/Maintenance/Assets/integrityData
  src/Maintenance/Interfaces/InfoRetrieverServiceInterface.php
  src/Maintenance/Interfaces/InstallDataSourceInterface.php
  src/Maintenance/Interfaces/ModuleInstallTypeInterface.php
  src/Maintenance/Services/ConfigInfoRetrieverService.php
  src/Maintenance/Services/InfoBuilderService.php
  src/Maintenance/Services/InstallDataSource/AbstractInstallDataSource.php
  src/Maintenance/Services/InstallDataSource/ComposerInstallDataSource.php
  src/Maintenance/Services/InstallDataSource/CoreInstallDataSource.php
  src/Maintenance/Services/InstallDataSource/ModmanInstallDataSource.php
  src/Maintenance/Services/IntegrityInfoRetrieverService.php
  src/Maintenance/Services/LogDownloadInfoRetrieverService.php
  src/Maintenance/Services/LogInfoRetrieverService.php
  src/Maintenance/Services/OrderInfoRetrieverService.php
  src/Maintenance/Services/PhpInfoRetrieverService.php
  src/Maintenance/Services/VersionInfoRetrieverService.php
  src/Webhook/Services/ChargeHandlerService.php
  src/Webhook/Services/OrderHandlerService.php
Labels: Ready, feature

#22 Fix invalid directory on scandir
  src/Maintenance/Services/LogInfoRetrieverService.php
Labels: Ready, bug
