Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-10, with the labels that each got.

#93 Improve recurrence configuration
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/ValueObjects/Configuration/RecurrenceConfig.php
Labels: :construction: In construction, :sparkles: Enhancement, :sparkles: Feature

#97 Fix credit card amount check
  src/Kernel/Services/MoneyService.php
Labels: :ambulance: Hotfix, :ok_hand: Ready

#99 Implement List entities method to list card saved
  src/Payment/Repositories/SavedCardRepository.php
Labels: :sparkles: Enhancement
