Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-04, with the labels that each got.

#36 Add multibuyer feature support.
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Maintenance/Assets/integrityData
  src/Payment/Factories/AddressFactory.php
  src/Payment/Factories/CustomerFactory.php
  src/Payment/Factories/PaymentFactory.php
Labels: Ready, feature

#34 Multi-store integrations
  README.md
  contributing.md
  maturity.json
  src/Kernel/Abstractions/AbstractEntity.php
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Repositories/ConfigurationRepository.php
  src/Maintenance/Assets/integrityData
  src/Maintenance/Services/ConfigInfoRetrieverService.php
Labels: Ready, enhancement

#41 Fix multi store verification and add more fields to saved credit card table
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Payment/Aggregates/SavedCard.php
  src/Payment/Factories/SavedCardFactory.php
  src/Payment/Repositories/SavedCardRepository.php
Labels: Ready, bug

#42 Merge develop into master
  composer.json
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Services/LogService.php
  src/Maintenance/Assets/integrityData
  src/Payment/Aggregates/SavedCard.php
  src/Payment/Factories/SavedCardFactory.php
  src/Payment/Repositories/SavedCardRepository.php
Labels: :bug: Bug

#40 Create Recurrence Config Value Object and add on configuration
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/ValueObjects/Configuration/RecurrenceConfig.php
Labels: :ok_hand: Ready, enhancement

#44 Add new error messages.
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
Labels: :ok_hand: Ready, :sparkles: Enhancement

#43 Migrate recurrence template to core
  src/Kernel/Abstractions/AbstractDatabaseDecorator.php
  src/Recurrence/Aggregates/RecurrencyProduct.php
  src/Recurrence/Aggregates/Repetition.php
  src/Recurrence/Aggregates/Template.php
  src/Recurrence/Factories/TemplateFactory.php
  src/Recurrence/Repositories/TemplateRepository.php
  src/Recurrence/Services/TemplateService.php
  src/Recurrence/ValueObjects/DiscountValueObject.php
  src/Recurrence/ValueObjects/DueValueObject.php
  src/Recurrence/ValueObjects/IntervalValueObject.php
Labels: :ok_hand: Ready, :sparkles: Feature

#45 Fix antifraud sending
  src/Kernel/Factories/ConfigurationFactory.php
  src/Payment/Aggregates/Order.php
Labels: :bug: Bug, :ok_hand: Ready

#49 Fix address index check
  README.md
  composer.json
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Maintenance/Assets/integrityData
  src/Payment/Aggregates/Customer.php
  src/Payment/Aggregates/Item.php
  src/Payment/Aggregates/Order.php
  src/Payment/Services/ResponseHandlers/ErrorExceptionHandler.php
Labels: :bug: Bug, :ok_hand: Ready

#48 Create capture charge
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Interfaces/PlatformOrderInterface.php
  src/Kernel/Repositories/OrderRepository.php
  src/Kernel/Responses/ServiceResponse.php
  src/Kernel/Services/APIService.php
  src/Kernel/Services/ChargeService.php
  src/Payment/Services/ResponseHandlers/OrderHandler.php
  src/Webhook/Services/ChargeHandlerService.php
Labels: :ok_hand: Ready, :sparkles: Enhancement
