Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-03, with the labels that each got.

#24 Fix some hard code
  src/Hub/Commands/AbstractCommand.php
  src/Hub/Commands/CommandType.php
  src/Hub/Services/HubIntegrationService.php
  src/Kernel/Interfaces/CommandInterface.php
  src/Maintenance/Assets/integrityData
  src/Maintenance/Services/InstallDataSource/AbstractInstallDataSource.php
  src/Maintenance/Services/IntegrityInfoRetrieverService.php
Labels: Ready, bug

#25 Add card payment method
  src/Kernel/Abstractions/AbstractDataService.php
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
  src/Kernel/Abstractions/AbstractPlatformOrderDecorator.php
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Aggregates/LogObject.php
  src/Kernel/Aggregates/Order.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Factories/LogObjectFactory.php
  src/Kernel/Factories/TransactionFactory.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Interfaces/PlatformOrderInterface.php
  src/Kernel/Log/JsonPrettyFormatter.php
  src/Kernel/Services/APIService.php
  src/Kernel/Services/LogService.php
  src/Kernel/Services/OrderLogService.php
  src/Kernel/Services/OrderService.php
  src/Kernel/Services/VersionService.php
  src/Kernel/ValueObjects/Configuration/AddressAttributes.php
  src/Kernel/ValueObjects/Id/CustomerId.php
  src/Kernel/ValueObjects/NumericString.php
  src/Kernel/ValueObjects/TransactionStatus.php
  src/Kernel/ValueObjects/VersionInfo.php
  src/Maintenance/Assets/integrityData
  src/Maintenance/Services/InfoBuilderService.php
  src/Maintenance/Services/InstallDataSource/AbstractInstallDataSource.php
  src/Maintenance/Services/InstallDataSource/ComposerInstallDataSource.php
  src/Maintenance/Services/InstallDataSource/CoreInstallDataSource.php
  src/Maintenance/Services/InstallDataSource/ModmanInstallDataSource.php
  src/Maintenance/Services/VersionInfoRetrieverService.php
  src/Payment/Aggregates/Address.php
  src/Payment/Aggregates/Customer.php
  src/Payment/Aggregates/Item.php
  src/Payment/Aggregates/Order.php
  src/Payment/Aggregates/Payments/AbstractCreditCardPayment.php
  src/Payment/Aggregates/Payments/AbstractPayment.php
  src/Payment/Aggregates/Payments/BoletoPayment.php
  src/Payment/Aggregates/Payments/NewCreditCardPayment.php
  src/Payment/Aggregates/Payments/SavedCreditCardPayment.php
  src/Payment/Aggregates/Shipping.php
  src/Payment/Factories/PaymentFactory.php
  src/Payment/Interfaces/ConvertibleToSDKRequestsInterface.php
  src/Payment/Interfaces/ResponseHandlerInterface.php
  src/Payment/Services/ResponseHandlers/AbstractResponseHandler.php
  src/Payment/Services/ResponseHandlers/ErrorExceptionHandler.php
  src/Payment/Services/ResponseHandlers/OrderHandler.php
  src/Payment/Traits/WithAmountTrait.php
  src/Payment/Traits/WithCustomerTrait.php
  src/Payment/ValueObjects/AbstractCardIdentifier.php
  src/Payment/ValueObjects/BoletoBank.php
  src/Payment/ValueObjects/CardId.php
  src/Payment/ValueObjects/CardToken.php
  src/Payment/ValueObjects/CustomerPhones.php
  src/Payment/ValueObjects/CustomerType.php
  src/Payment/ValueObjects/PaymentMethod.php
  src/Payment/ValueObjects/Phone.php
  src/Webhook/Services/OrderHandlerService.php
Labels: Ready, feature

#27 Add support to float item quantity
  src/Maintenance/Assets/integrityData
  src/Payment/Aggregates/Item.php
Labels: Ready, bug, enhancement

#30 Add Boleto Payment Method and Save Cards
  src/Kernel/Abstractions/AbstractDatabaseDecorator.php
  src/Kernel/Aggregates/Charge.php
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Aggregates/Order.php
  src/Kernel/Aggregates/Transaction.php
  src/Kernel/Factories/ChargeFactory.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Factories/OrderFactory.php
  src/Kernel/Factories/TransactionFactory.php
  src/Kernel/Repositories/ChargeRepository.php
  src/Kernel/Repositories/TransactionRepository.php
  src/Kernel/Services/APIService.php
  src/Maintenance/Assets/integrityData
  src/Payment/Aggregates/Customer.php
  src/Payment/Aggregates/Order.php
  src/Payment/Aggregates/Payments/AbstractCreditCardPayment.php
  src/Payment/Aggregates/Payments/AbstractPayment.php
  src/Payment/Aggregates/Payments/NewCreditCardPayment.php
  src/Payment/Aggregates/Payments/SavedCreditCardPayment.php
  src/Payment/Aggregates/SavedCard.php
  src/Payment/Factories/CustomerFactory.php
  src/Payment/Factories/PaymentFactory.php
  src/Payment/Factories/SavedCardFactory.php
  src/Payment/Interfaces/HaveOrderInterface.php
  src/Payment/Repositories/CustomerRepository.php
  src/Payment/Repositories/SavedCardRepository.php
  src/Payment/Services/ResponseHandlers/OrderHandler.php
  src/Payment/Traits/WithOrderTrait.php
  src/Webhook/Exceptions/WebhookAlreadyHandledException.php
Labels: Ready, feature

#35 Add a Codacy badge to README.md
  README.md
Labels: Ready, enhancement
