Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-07, with the labels that each got.

#75 Implement save card function to auth only option
  src/Kernel/Aggregates/Charge.php
  src/Kernel/Aggregates/Transaction.php
  src/Kernel/Factories/ChargeFactory.php
  src/Kernel/Factories/TransactionFactory.php
  src/Kernel/Repositories/ChargeRepository.php
  src/Kernel/Repositories/TransactionRepository.php
  src/Kernel/Services/OrderService.php
  src/Payment/Factories/SavedCardFactory.php
  src/Payment/Services/ResponseHandlers/OrderHandler.php
Labels: :bug: Bug, :ok_hand: Ready, :sparkles: Enhancement

#76 Fix installment service when use installment default config
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Services/InstallmentService.php
  src/Payment/Services/ValidationService.php
Labels: :bug: Bug, :ok_hand: Ready

#78 Fix the bug on first purchase using a saved card
  src/Payment/Aggregates/Payments/NewCreditCardPayment.php
Labels: :bug: Bug, :ok_hand: Ready

#79 Remove special characters from phone numbers
  src/Payment/Factories/CustomerFactory.php
  src/Payment/ValueObjects/Phone.php
Labels: :bug: Bug, :ok_hand: Ready

#80 Merge develop into master
  composer.json
  src/Maintenance/Assets/integrityData
  src/Payment/Aggregates/Payments/NewCreditCardPayment.php
  src/Payment/Factories/CustomerFactory.php
  src/Payment/ValueObjects/Phone.php
Labels: :bug: Bug, :ok_hand: Ready

#81 Added messages on i18n file
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
Labels: :ok_hand: Ready, :sparkles: Enhancement
