Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-05, with the labels that each got.

#51 Saved cards fixes
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/ValueObjects/AbstractValidString.php
  src/Payment/Aggregates/SavedCard.php
  src/Payment/Factories/SavedCardFactory.php
  src/Payment/Repositories/SavedCardRepository.php
  src/Payment/Services/ResponseHandlers/OrderHandler.php
Labels: :bug: Bug, :ok_hand: Ready

#53 Partial capture fixes
  src/Kernel/Abstractions/AbstractInvoiceDecorator.php
  src/Kernel/Abstractions/AbstractPlatformOrderDecorator.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Interfaces/PlatformInvoiceInterface.php
  src/Kernel/Interfaces/PlatformOrderInterface.php
  src/Kernel/Repositories/OrderRepository.php
  src/Maintenance/Assets/integrityData
  src/Webhook/Exceptions/UnprocessableWebhookException.php
  src/Webhook/Exceptions/WebhookAlreadyHandledException.php
  src/Webhook/Services/ChargeHandlerService.php
  src/Webhook/Services/OrderHandlerService.php
Labels: :bug: Bug, :ok_hand: Ready

#55 Create functional tests structure
  behat.yml
  composer.json
  composer.lock
  tests/Functional/Features/Bootstrap/CoreFeature.php
  tests/Functional/Features/BuyUsingCreditCard.feature
Labels: :sparkles: Enhancement

#56 Merge develop into master
  behat.yml
  composer.json
  composer.lock
  src/Maintenance/Assets/integrityData
  tests/Functional/Features/Bootstrap/CoreFeature.php
  tests/Functional/Features/BuyUsingCreditCard.feature
Labels: :ok_hand: Ready, :sparkles: Enhancement

#57 Remove Behat.
  behat.yml
  composer.json
  tests/Functional/Features/Bootstrap/CoreFeature.php
  tests/Functional/Features/BuyUsingCreditCard.feature
Labels: :ambulance: Hotfix, :ok_hand: Ready

#58 Create customer service to update customer at Mundipagg
  src/Kernel/Interfaces/PlatformCustomerInterface.php
  src/Kernel/Services/APIService.php
  src/Payment/Aggregates/Customer.php
  src/Payment/Factories/CustomerFactory.php
  src/Payment/Services/CustomerService.php
Labels: :ok_hand: Ready, :sparkles: Enhancement

#62 Create method to delete customer by code on customer service
  src/Payment/Repositories/CustomerRepository.php
  src/Payment/Services/CustomerService.php
  src/Payment/Services/ResponseHandlers/OrderHandler.php
Labels: :ok_hand: Ready, :sparkles: Feature

#64 Added log of Customer Request
  src/Payment/Services/CustomerService.php
Labels: :ok_hand: Ready, :sparkles: Enhancement

#63 Fix static methods, duplicated configuration and \Throwable issues
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
  src/Kernel/Abstractions/AbstractPlatformOrderDecorator.php
  src/Kernel/Factories/ConfigurationFactory.php
Labels: :bug: Bug, :ok_hand: Ready

#65 Fix configuration issues
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
Labels: :bug: Bug, :ok_hand: Ready

#66 Fix Exceptions bug on PHP 7.*
  src/Kernel/Abstractions/AbstractPlatformOrderDecorator.php
  src/Kernel/Factories/ConfigurationFactory.php
Labels: :bug: Bug, :ok_hand: Ready
