Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-11, with the labels that each got.

#100 Add tests and bug fix
  .circleci/config.yml
  .gitignore
  .phpunit.result.cache
  Dockerfile
  composer.json
  composer.lock
  docker-compose.yml
  hooks/pre-commit
  phpunit.xml
  src/Hub/Aggregates/InstallToken.php
  src/Hub/ValueObjects/HubInstallToken.php
  src/Kernel/Abstractions/AbstractValueObject.php
  src/Kernel/Aggregates/Charge.php
  src/Kernel/Aggregates/Transaction.php
  src/Kernel/Services/OrderService.php
  src/Kernel/ValueObjects/CardBrand.php
  src/Kernel/ValueObjects/Id/AccountId.php
  src/Kernel/ValueObjects/Id/ChargeId.php
  src/Kernel/ValueObjects/Id/CustomerId.php
  src/Kernel/ValueObjects/Id/GUID.php
  src/Kernel/ValueObjects/Id/MerchantId.php
  src/Kernel/ValueObjects/Id/OrderId.php
  src/Kernel/ValueObjects/Id/TransactionId.php
  src/Kernel/ValueObjects/Installment.php
  src/Kernel/ValueObjects/Key/HubAccessTokenKey.php
  src/Kernel/ValueObjects/Key/PublicKey.php
  src/Kernel/ValueObjects/Key/SecretKey.php
  src/Kernel/ValueObjects/Key/TestPublicKey.php
  src/Kernel/ValueObjects/Key/TestSecretKey.php
  src/Kernel/ValueObjects/VersionInfo.php
  tests/Hub/Aggregates/InstallTokenTests.php
  tests/Kernel/Aggregates/ChargeTests.php
  tests/Kernel/ValueObjects/AbstractValidStringTest.php
  tests/Kernel/ValueObjects/CardBrandTest.php
  tests/Kernel/ValueObjects/ChargeStatusTest.php
  tests/Kernel/ValueObjects/Id/AccountIdTest.php
  tests/Kernel/ValueObjects/Id/ChargeIdTest.php
  tests/Kernel/ValueObjects/Id/CustomerIdTest.php
  tests/Kernel/ValueObjects/Id/GUIDTest.php
  tests/Kernel/ValueObjects/Id/MerchantIdTest.php
  tests/Kernel/ValueObjects/Id/OrderIdTest.php
  tests/Kernel/ValueObjects/Id/TransactionIdTest.php
  tests/Kernel/ValueObjects/InstallmentTest.php
  tests/Kernel/ValueObjects/InvoiceStateTest.php
  tests/Kernel/ValueObjects/Key/HubAccessTokenKeyTest.php
  tests/Kernel/ValueObjects/Key/PublicKeyTest.php
  tests/Kernel/ValueObjects/Key/SecretKeyTest.php
  tests/Kernel/ValueObjects/Key/TestPublicKeyTest.php
  tests/Kernel/ValueObjects/Key/TestSecretKeyTest.php
  tests/Kernel/ValueObjects/NumericStringTest.php
  tests/Kernel/ValueObjects/OrderStateTest.php
  tests/Kernel/ValueObjects/OrderStatusTest.php
  tests/Kernel/ValueObjects/TransactionStatusTest.php
  tests/Kernel/ValueObjects/TransactionTypeTest.php
  tests/Kernel/ValueObjects/ValidStringTestTrait.php
  tests/Kernel/ValueObjects/VersionInfoTest.php
  tests/mock/ValidStringMock.php
Labels: :bug: Bug, :ok_hand: Ready, :sparkles: Feature

#102 Merge develop into master
  src/Kernel/Services/OrderService.php
  src/Maintenance/Assets/integrityData
Labels: :ambulance: Hotfix, :ok_hand: Ready

#101 Create CRUD subscription
  composer.json
  composer.lock
  phpunit.xml
  src/Kernel/Abstractions/AbstractDatabaseDecorator.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Interfaces/PlatformProductInterface.php
  src/Recurrence/Aggregates/Plan.php
  src/Recurrence/Aggregates/ProductSubscription.php
  src/Recurrence/Aggregates/RecurrencyProduct.php
  src/Recurrence/Aggregates/Repetition.php
  src/Recurrence/Aggregates/SubProduct.php
  src/Recurrence/Aggregates/Template.php
  src/Recurrence/Factories/PlanFactory.php
  src/Recurrence/Factories/ProductSubscriptionFactory.php
  src/Recurrence/Factories/RepetitionFactory.php
  src/Recurrence/Factories/SubProductFactory.php
  src/Recurrence/Factories/TemplateFactory.php
  src/Recurrence/Interfaces/RecurrenceEntityInterface.php
  src/Recurrence/Interfaces/SubProductEntityInterface.php
  src/Recurrence/Repositories/PlanRepository.php
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Recurrence/Repositories/RepetitionRepository.php
  src/Recurrence/Repositories/SubProductRepository.php
  src/Recurrence/Repositories/TemplateRepository.php
  src/Recurrence/Services/PlanService.php
  src/Recurrence/Services/ProductSubscriptionService.php
  src/Recurrence/Services/TemplateService.php
  src/Recurrence/ValueObjects/DiscountValueObject.php
  src/Recurrence/ValueObjects/IntervalValueObject.php
  src/Recurrence/ValueObjects/PlanId.php
  src/Recurrence/ValueObjects/PricingSchemeValueObject.php
  tests/Recurrence/Aggregates/PlanTests.php
  tests/Recurrence/Factories/PlanTests.php
Labels: :ok_hand: Ready, :sparkles: Feature

#103 Create recurrence service and add attribute on subscription product
  src/Recurrence/Aggregates/ProductSubscription.php
  src/Recurrence/Factories/ProductSubscriptionFactory.php
  src/Recurrence/Interfaces/RecurrenceEntityInterface.php
  src/Recurrence/Repositories/PlanRepository.php
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Recurrence/Services/PlanService.php
  src/Recurrence/Services/ProductSubscriptionService.php
  src/Recurrence/Services/RecurrenceService.php
Labels: :ok_hand: Ready

#105 Create recurrence product CRUD API
  src/Kernel/Abstractions/AbstractDatabaseDecorator.php
  src/Recurrence/Aggregates/ProductSubscription.php
  src/Recurrence/Aggregates/Repetition.php
  src/Recurrence/Factories/ProductSubscriptionFactory.php
  src/Recurrence/Factories/RepetitionFactory.php
  src/Recurrence/Interfaces/ProductSubscriptionInterface.php
  src/Recurrence/Interfaces/RepetitionInterface.php
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Recurrence/Repositories/RepetitionRepository.php
  src/Recurrence/Services/ProductSubscriptionService.php
  tests/Recurrence/Aggregates/ProductSubscriptionTest.php
  tests/Recurrence/Aggregates/RepetitionTest.php
  tests/Recurrence/Factories/ProductSubscriptionFactoryTest.php
  tests/Recurrence/Factories/RepetitionFactoryTest.php
Labels: :ok_hand: Ready, :sparkles: Feature
