Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-06, with the labels that each got.

#68 Create validation service and added business rules to aggregates
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Payment/Aggregates/Address.php
  src/Payment/Aggregates/Customer.php
  src/Payment/Services/ValidationService.php
Labels: :ok_hand: Ready, :sparkles: Enhancement

#70 Remove method param type
  src/Kernel/Aggregates/Configuration.php
Labels: :bug: Bug, :ok_hand: Ready

#71 Merge develop into master
  composer.json
  src/Kernel/Aggregates/Configuration.php
  src/Maintenance/Assets/integrityData
Labels: :bug: Bug, :ok_hand: Ready

#72 Change hub names to snake case format
  src/Hub/Factories/HubCommandFactory.php
  src/Hub/Services/HubIntegrationService.php
  src/Maintenance/Assets/integrityData
Labels: :ambulance: Hotfix, :ok_hand: Ready

#74 Change order structure to prevent failed order creation
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Services/APIService.php
  src/Kernel/Services/OrderService.php
  src/Payment/Services/ResponseHandlers/ErrorExceptionHandler.php
  src/Payment/Services/ResponseHandlers/OrderHandler.php
Labels: :sparkles: Enhancement
