Repository mundipagg/ecommerce-module-core, pull requests merged in 2019-01, with the labels that each got.

#3 Fix boleto webhook and add underpaid handling
  src/Kernel/Aggregates/Charge.php
  src/Kernel/Factories/TransactionFactory.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/ValueObjects/TransactionType.php
  src/Webhook/Services/ChargeHandlerService.php
Labels: Ready, bug, enhancement, feature

#5 Cancel order from platform
  composer.json
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
  src/Kernel/Aggregates/Charge.php
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ChargeFactory.php
  src/Kernel/Factories/TransactionFactory.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Interfaces/PlatformOrderInterface.php
  src/Kernel/Repositories/ConfigurationRepository.php
  src/Kernel/Services/APIService.php
  src/Kernel/Services/OrderService.php
  src/Kernel/ValueObjects/TransactionStatus.php
  src/Webhook/Services/ChargeHandlerService.php
  src/Webhook/Services/OrderHandlerService.php
Labels: Ready, feature

#6 Add installment service
  src/Kernel/Abstractions/AbstractModuleCoreSetup.php
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Aggregates/Transaction.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Repositories/TransactionRepository.php
  src/Kernel/Services/InstallmentService.php
  src/Kernel/ValueObjects/CardBrand.php
  src/Kernel/ValueObjects/Configuration/CardConfig.php
  src/Kernel/ValueObjects/Installment.php
Labels: Ready, feature

#8 Handle missing parameters on installment configuration.
  src/Kernel/ValueObjects/Configuration/CardConfig.php
Labels: Ready, bug

#10 Handle missing parameters on installment configuration.
  src/Kernel/ValueObjects/Configuration/CardConfig.php
Labels: Ready, bug

#12 Fix additional info update
  src/Kernel/Aggregates/Transaction.php
  src/Kernel/Factories/TransactionFactory.php
  src/Webhook/Services/ChargeHandlerService.php
  src/Webhook/Services/OrderHandlerService.php
Labels: Ready, bug

#15 Fix OrderID empty on cancel order at mundipagg
  composer.json
  src/Kernel/Services/OrderService.php
  src/Kernel/Services/VersionService.php
Labels: Ready, bug
