Repository mundipagg/ecommerce-module-core, pull requests merged in 2020-01, with the labels that each got.

#118 Fix bug on charge handle webhook
  src/Recurrence/Factories/RepetitionFactory.php
  src/Recurrence/Repositories/ChargeRepository.php
  src/Webhook/Services/ChargeRecurrenceService.php
Labels: :bug: Bug, :ok_hand: Ready

#119 Create subscription at Mundipagg
  src/Kernel/Factories/ChargeFactory.php
  src/Kernel/Factories/OrderFactory.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Services/APIService.php
  src/Recurrence/Aggregates/Charge.php
  src/Recurrence/Aggregates/Increment.php
  src/Recurrence/Aggregates/Invoice.php
  src/Recurrence/Aggregates/SubProduct.php
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Factories/ChargeFactory.php
  src/Recurrence/Factories/InvoiceFactory.php
  src/Recurrence/Factories/SubscriptionFactory.php
  src/Recurrence/Repositories/ChargeRepository.php
  src/Recurrence/Repositories/SubscriptionRepository.php
  src/Recurrence/Services/ResponseHandlers/AbstractResponseHandler.php
  src/Recurrence/Services/ResponseHandlers/ChargeHandler.php
  src/Recurrence/Services/ResponseHandlers/SubscriptionHandler.php
  src/Recurrence/Services/SubscriptionService.php
  src/Recurrence/ValueObjects/SubscriptionStatus.php
  tests/Recurrence/Factories/PlanTests.php
Labels: :ok_hand: Ready, :sparkles: Feature

#120 Add more unit tests
  src/Recurrence/Aggregates/Invoice.php
  tests/Recurrence/Aggregates/InvoiceTests.php
Labels: :ok_hand: Ready, :sparkles: Enhancement

#122 Add tests
  composer.json
  src/Recurrence/Aggregates/Charge.php
  src/Recurrence/Aggregates/Increment.php
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Factories/CycleFactory.php
  src/Recurrence/Repositories/ChargeRepository.php
  src/Recurrence/Services/RecurrenceService.php
  src/Recurrence/ValueObjects/DiscountValueObject.php
  src/Recurrence/ValueObjects/DueValueObject.php
  tests/Abstractions/AbstractRepositoryTest.php
  tests/Abstractions/AbstractSetupTest.php
  tests/Recurrence/Aggregates/ChargeTest.php
  tests/Recurrence/Aggregates/CycleTest.php
  tests/Recurrence/Aggregates/IncrementTest.php
  tests/Recurrence/Aggregates/InvoiceTest.php
  tests/Recurrence/Aggregates/PlanTest.php
  tests/Recurrence/Aggregates/SubProductTest.php
  tests/Recurrence/Aggregates/SubscriptionTest.php
  tests/Recurrence/Factories/ChargeFactoryTest.php
  tests/Recurrence/Factories/CycleFactoryTest.php
  tests/Recurrence/Factories/PlanTest.php
  tests/Recurrence/Repositories/ProductSubscriptionRepositoryTest.php
  tests/Recurrence/Repositories/SubProductRepositoryTest.php
  tests/Recurrence/Services/ProductSubscriptionServiceTest.php
  tests/Recurrence/Services/RecurrenceServiceTest.php
  tests/Recurrence/ValueObjects/DueValueObjectTest.php
  tests/Recurrence/ValueObjects/Id/PlanIdTest.php
  tests/Recurrence/ValueObjects/SubscriptionStatusTest.php
  tests/mock/Concrete/Migrate.php
  tests/mock/Concrete/PlatformDatabaseDecorator.php
Labels: :ok_hand: Ready, :sparkles: Enhancement

#124 Send e-mail change order status
  src/Kernel/Abstractions/AbstractPlatformOrderDecorator.php
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Interfaces/PlatformOrderInterface.php
  src/Kernel/Services/ChargeService.php
  src/Kernel/Services/OrderService.php
  src/Payment/Services/ResponseHandlers/OrderHandler.php
  src/Webhook/Services/OrderHandlerService.php
Labels: :sparkles: Enhancement, :sparkles: Feature

#123 Fix wrong search by client
  src/Recurrence/Repositories/SubscriptionRepository.php
  src/Recurrence/Services/SubscriptionService.php
Labels: :bug: Bug, :ok_hand: Ready

#125 Merge into master
  README.md
  composer.json
  src/Kernel/Abstractions/AbstractPlatformOrderDecorator.php
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/Interfaces/PlatformOrderInterface.php
  src/Kernel/Services/ChargeService.php
  src/Kernel/Services/OrderService.php
  src/Maintenance/Assets/integrityData
  src/Payment/Services/ResponseHandlers/OrderHandler.php
  src/Webhook/Services/OrderHandlerService.php
Labels: :sparkles: Enhancement, :sparkles: Feature

#128 Fix send of cycles with empty value
  src/Recurrence/Services/SubscriptionService.php
Labels: :bug: Bug, :ok_hand: Ready

#126 Fix webhook recurrence
  src/Kernel/Factories/OrderFactory.php
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Factories/ChargeFactory.php
  src/Recurrence/Factories/SubscriptionFactory.php
  src/Recurrence/Repositories/ChargeRepository.php
  src/Recurrence/Repositories/SubscriptionRepository.php
  src/Recurrence/Services/ResponseHandlers/ChargeHandler.php
  src/Recurrence/Services/ResponseHandlers/SubscriptionHandler.php
  src/Recurrence/Services/SubscriptionService.php
  src/Webhook/Services/ChargeRecurrenceService.php
  tests/Recurrence/Aggregates/SubscriptionTest.php
Labels: :bug: Bug, :ok_hand: Ready

#129 Feature mod 897 create invoice cancel
  .circleci/config.yml
  src/Kernel/Services/APIService.php
  src/Recurrence/Aggregates/Charge.php
  src/Recurrence/Factories/ChargeFactory.php
  src/Recurrence/Factories/InvoiceFactory.php
  src/Recurrence/Factories/SubscriptionFactory.php
  src/Recurrence/Repositories/ChargeRepository.php
  src/Recurrence/Services/InvoiceService.php
  src/Recurrence/Services/SubscriptionService.php
  src/Recurrence/ValueObjects/InvoiceIdValueObject.php
  src/Recurrence/ValueObjects/InvoiceStatus.php
  tests/Recurrence/Aggregates/ChargeTest.php
  tests/Recurrence/Factories/ChargeFactoryTest.php
  tests/Recurrence/Services/Invoice.php
  tests/mock/Concrete/Migrate.php
  tests/mock/Concrete/PlatformDatabaseDecorator.php
Labels: :sparkles: Feature

#130 Create api plan
  src/Recurrence/Aggregates/Plan.php
  src/Recurrence/Aggregates/Repetition.php
  src/Recurrence/Aggregates/SubProduct.php
  src/Recurrence/Factories/PlanFactory.php
  src/Recurrence/Interfaces/ProductPlanInterface.php
  src/Recurrence/Repositories/PlanRepository.php
  src/Recurrence/Services/PlanService.php
  src/Recurrence/ValueObjects/PricingSchemeValueObject.php
Labels: :sparkles: Enhancement, :sparkles: Feature

#134 Fix statement descriptor
  src/Kernel/Aggregates/Configuration.php
Labels: :bug: Bug

#133 Fix webhook subscription
  src/Kernel/Factories/OrderFactory.php
  src/Webhook/Services/SubscriptionHandlerService.php
Labels: :bug: Bug

#135 Fix statement descriptor
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Helper/StringFunctionsHelper.php
Labels: :bug: Bug

#136 Merge develop into master
  composer.json
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Helper/StringFunctionsHelper.php
Labels: :bug: Bug

#137 Fix get boleto url method
  src/Recurrence/Aggregates/Charge.php
  src/Recurrence/Factories/ChargeFactory.php
  tests/Recurrence/Aggregates/ChargeTest.php
Labels: :bug: Bug

#139 Add statement descriptor to subscription request.
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Services/SubscriptionService.php
Labels: :bug: Bug

#140 Change subscription creation
  src/Recurrence/Services/SubscriptionService.php
  tests/Recurrence/Services/InvoiceServiceTest.php
Labels: :bug: Bug, :construction: In construction

#138 Change Product Recurrence to set the cycle on the repetitions
  src/Recurrence/Aggregates/ProductSubscription.php
  src/Recurrence/Aggregates/Repetition.php
  src/Recurrence/Factories/ProductSubscriptionFactory.php
  src/Recurrence/Factories/RepetitionFactory.php
  src/Recurrence/Interfaces/ProductSubscriptionInterface.php
  src/Recurrence/Interfaces/RepetitionInterface.php
  src/Recurrence/Repositories/ProductSubscriptionRepository.php
  src/Recurrence/Repositories/RepetitionRepository.php
  src/Recurrence/Services/ProductSubscriptionService.php
  src/Recurrence/Services/SubscriptionService.php
  src/Webhook/Services/ChargeRecurrenceService.php
  tests/Recurrence/Aggregates/ProductSubscriptionTest.php
  tests/Recurrence/Aggregates/RepetitionTest.php
  tests/Recurrence/Factories/ProductSubscriptionFactoryTest.php
  tests/Recurrence/Factories/RepetitionFactoryTest.php
  tests/Recurrence/Repositories/ProductSubscriptionRepositoryTest.php
  tests/Recurrence/Repositories/RepetitionRepositoryTest.php
  tests/Recurrence/Services/InvoiceServiceTest.php
  tests/Recurrence/Services/ProductSubscriptionServiceTest.php
  tests/mock/Concrete/Migrate.php
Labels: :bug: Bug, :construction: In construction
