Repository mundipagg/ecommerce-module-core, pull requests merged in 2020-11, with the labels that each got.

#199 [Enhancement] Adds config snapshot when create order
  src/Kernel/Services/APIService.php
Labels: :sparkles: Enhancement

#201 [Bugfix] removes special characters
  src/Kernel/Helper/StringFunctionsHelper.php
  src/Kernel/Repositories/ChargeRepository.php
  src/Kernel/Repositories/TransactionRepository.php
  src/Payment/Aggregates/Address.php
Labels: :bug: Bug

#202 [Feature] Magento Pix
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Factories/Configurations/PixConfigFactory.php
  src/Kernel/ValueObjects/Configuration/PixConfig.php
  src/Kernel/ValueObjects/PaymentMethod.php
  src/Kernel/ValueObjects/TransactionStatus.php
  src/Kernel/ValueObjects/TransactionType.php
  src/Payment/Aggregates/Order.php
  src/Payment/Aggregates/Payments/PixPayment.php
  src/Payment/Factories/PaymentFactory.php
  src/Payment/Services/OrderService.php
  src/Payment/ValueObjects/PaymentMethod.php
  src/Payment/ValueObjects/PixBank.php
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Services/SubscriptionService.php
  tests/Kernel/ValueObjects/TransactionStatusTest.php
  tests/Kernel/ValueObjects/TransactionTypeTest.php
Labels: :ok_hand: Ready, :sparkles: Feature
