Repository mundipagg/ecommerce-module-core, pull requests merged in 2020-08, with the labels that each got.

#189 Fix recurrence subscription with Pagarme gateway
  src/Recurrence/Aggregates/Subscription.php
Labels: :bug: Bug

#191 Fix round precision on Money Service
  src/Kernel/Services/MoneyService.php
Labels: :ambulance: Hotfix, :ok_hand: Ready

#190 Added messages to I18N service
  .github/PULL_REQUEST_TEMPLATE.md
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
Labels: :ok_hand: Ready, :sparkles: Enhancement

#192 Avoid cancel order after status closed
  src/Kernel/Services/ChargeService.php
  src/Kernel/Services/OrderService.php
  src/Webhook/Services/OrderHandlerService.php
Labels: :bug: Bug

#193 Change way to convert to float and using the money service to get correct instalment values
  src/Kernel/Services/InstallmentService.php
  src/Kernel/ValueObjects/Installment.php
Labels: :bug: Bug
