Repository mundipagg/ecommerce-module-core, pull requests merged in 2020-04, with the labels that each got.

#162 Create invoice service handler
  src/Kernel/Abstractions/AbstractDatabaseDecorator.php
  src/Kernel/Factories/Configurations/RecurrenceConfigFactory.php
  src/Kernel/Interfaces/PlatformProductInterface.php
  src/Kernel/ValueObjects/Configuration/RecurrenceConfig.php
  src/Payment/Aggregates/Item.php
  src/Recurrence/Aggregates/Cycle.php
  src/Recurrence/Aggregates/Invoice.php
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Aggregates/SubscriptionItem.php
  src/Recurrence/Factories/CycleFactory.php
  src/Recurrence/Factories/InvoiceFactory.php
  src/Recurrence/Factories/SubscriptionFactory.php
  src/Recurrence/Factories/SubscriptionItemFactory.php
  src/Recurrence/Repositories/SubscriptionItemRepository.php
  src/Recurrence/Repositories/SubscriptionRepository.php
  src/Recurrence/Services/RecurrenceService.php
  src/Recurrence/Services/SubscriptionItemService.php
  src/Recurrence/Services/SubscriptionService.php
  src/Recurrence/ValueObjects/SubscriptionItemId.php
  src/Webhook/Aggregates/Webhook.php
  src/Webhook/Services/InvoiceHandlerService.php
  src/Webhook/Services/InvoiceRecurrenceService.php
  tests/Recurrence/Services/CartRules/MoreThanOneRecurrenceProductTest.php
Labels: :sparkles: Enhancement, :sparkles: Feature

#163 Change if to save voucher-card
  src/Payment/Services/ResponseHandlers/OrderHandler.php
Labels: :sparkles: Enhancement, :sparkles: Feature

#164 Create debit configurations
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Factories/Configurations/DebitConfigFactory.php
  src/Kernel/ValueObjects/Configuration/DebitConfig.php
Labels: :construction: In construction, :sparkles: Feature

#165 Add logs to plan creation request
  src/Recurrence/Services/PlanService.php
Labels: :ok_hand: Ready, :sparkles: Enhancement

#166 Create debit transaction
  src/Kernel/ValueObjects/TransactionType.php
  src/Payment/Aggregates/Order.php
  src/Payment/Aggregates/Payments/NewCreditCardPayment.php
  src/Payment/Aggregates/Payments/NewDebitCardPayment.php
  src/Payment/Factories/PaymentFactory.php
  src/Payment/ValueObjects/PaymentMethod.php
  tests/Kernel/ValueObjects/TransactionTypeTest.php
Labels: :ok_hand: Ready, :sparkles: Feature

#167 Fix bug when the order creation return an ErrorException from API
  src/Kernel/Services/APIService.php
  src/Kernel/Services/OrderService.php
Labels: :bug: Bug, :ok_hand: Ready

#168 Remove some credit card configuration dependencies
  src/Kernel/Services/InstallmentService.php
  src/Kernel/ValueObjects/Configuration/DebitConfig.php
  src/Kernel/ValueObjects/Configuration/VoucherConfig.php
  src/Payment/Aggregates/Payments/NewDebitCardPayment.php
  src/Payment/Aggregates/Payments/NewVoucherPayment.php
  src/Payment/Factories/PaymentFactory.php
Labels: :bug: Bug
