Repository mundipagg/ecommerce-module-core, pull requests merged in 2020-03, with the labels that each got.

#150 Create subscription of plan
  src/Payment/Aggregates/Item.php
  src/Recurrence/Aggregates/Plan.php
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Factories/SubscriptionFactory.php
  src/Recurrence/Repositories/PlanRepository.php
  src/Recurrence/Repositories/SubscriptionRepository.php
  src/Recurrence/Services/PlanService.php
  src/Recurrence/Services/RecurrenceService.php
  src/Recurrence/Services/SubscriptionService.php
  src/Recurrence/ValueObjects/Id/PlanId.php
  src/Recurrence/ValueObjects/PlanId.php
  tests/Recurrence/Aggregates/SubscriptionTest.php
  tests/Recurrence/Services/RecurrenceServiceTest.php
  tests/Recurrence/ValueObjects/PlanIdTest.php
Labels: :ok_hand: Ready, :sparkles: Feature

#151 Fix installments on plan creation
  src/Recurrence/Aggregates/Plan.php
  src/Recurrence/Aggregates/SubProduct.php
  src/Recurrence/Services/SubscriptionService.php
  tests/Recurrence/Aggregates/SubProductTest.php
Labels: :bug: Bug, :ok_hand: Ready

#152 Create subscription details page
  src/Recurrence/Services/SubscriptionService.php
Labels: :ok_hand: Ready, :sparkles: Feature

#154 Deleting a plan at mundipagg
  src/Recurrence/Services/PlanService.php
Labels: :bug: Bug, :ok_hand: Ready

#153 Implementing the voucher payment method
  src/Kernel/Aggregates/Configuration.php
  src/Kernel/Factories/ConfigurationFactory.php
  src/Kernel/Factories/Configurations/RecurrenceConfigFactory.php
  src/Kernel/Factories/Configurations/VoucherConfigFactory.php
  src/Kernel/Factories/TransactionFactory.php
  src/Kernel/ValueObjects/CardBrand.php
  src/Kernel/ValueObjects/Configuration/VoucherConfig.php
  src/Kernel/ValueObjects/PaymentMethod.php
  src/Kernel/ValueObjects/TransactionType.php
  src/Payment/Aggregates/Order.php
  src/Payment/Aggregates/Payments/NewVoucherPayment.php
  src/Payment/Factories/PaymentFactory.php
  tests/Kernel/ValueObjects/TransactionTypeTest.php
Labels: :ok_hand: Ready, :sparkles: Feature

#155 Implementing update of plans item
  src/Kernel/Abstractions/AbstractEntity.php
  src/Recurrence/Aggregates/Plan.php
  src/Recurrence/Aggregates/SubProduct.php
  src/Recurrence/Factories/SubProductFactory.php
  src/Recurrence/Repositories/SubProductRepository.php
  src/Recurrence/Services/PlanService.php
  src/Recurrence/Services/SubProductService.php
  src/Recurrence/ValueObjects/PlanItemId.php
  tests/Recurrence/Aggregates/PlanTest.php
  tests/mock/Concrete/Migrate.php
Labels: :ok_hand: Ready, :sparkles: Feature

#156 Fix integration multi store
  README.md
  maturity.json
  src/Kernel/Aggregates/Configuration.php
Labels: :sparkles: Enhancement

#157 Conflict product plan
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Recurrence/Services/CartRules/CompatibleRecurrenceProducts.php
  src/Recurrence/Services/CartRules/CurrentProduct.php
  src/Recurrence/Services/CartRules/JustOneProductPlanInCart.php
  src/Recurrence/Services/CartRules/JustProductPlanInCart.php
  src/Recurrence/Services/CartRules/JustSelfProductPlanInCart.php
  src/Recurrence/Services/CartRules/MoreThanOneRecurrenceProduct.php
  src/Recurrence/Services/CartRules/NormalWithRecurrenceProduct.php
  src/Recurrence/Services/CartRules/ProductListInCart.php
Labels: :sparkles: Feature

#158 Remove set capture flag
  src/Payment/Aggregates/Order.php
Labels: :bug: Bug, :ok_hand: Ready

#159 Payment data details
  src/Kernel/Aggregates/Charge.php
  src/Kernel/Aggregates/Transaction.php
  src/Kernel/Factories/ChargeFactory.php
  src/Kernel/Repositories/ChargeRepository.php
  src/Kernel/Repositories/TransactionRepository.php
  src/Kernel/Services/OrderService.php
Labels: :sparkles: Enhancement

#160 Fix cart rule subscription
  src/Recurrence/Services/CartRules/MoreThanOneRecurrenceProduct.php
  tests/Recurrence/Services/CartRules/MoreThanOneRecurrenceProductTest.php
Labels: :bug: Bug

#161 Change interfaces adapt swagger
  composer.lock
  src/Recurrence/Aggregates/Plan.php
  src/Recurrence/Aggregates/Repetition.php
  src/Recurrence/Aggregates/SubProduct.php
  src/Recurrence/Interfaces/ProductPlanInterface.php
  src/Recurrence/Interfaces/SubProductEntityInterface.php
Labels: :ambulance: Hotfix, :bug: Bug
