Repository mundipagg/ecommerce-module-core, pull requests merged in 2020-02, with the labels that each got.

#142 Cancel multi method charge
  src/Kernel/Aggregates/Charge.php
  src/Kernel/Factories/ChargeFactory.php
  src/Kernel/Factories/OrderFactory.php
  src/Kernel/Repositories/ChargeRepository.php
  src/Kernel/Services/ChargeService.php
  src/Kernel/Services/OrderService.php
  src/Webhook/Services/ChargeHandlerService.php
  src/Webhook/Services/ChargeOrderService.php
Labels: :bug: Bug, :sparkles: Enhancement

#143 Create charge subscription webhook
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Webhook/Services/AbstractHandlerService.php
  src/Webhook/Services/ChargeRecurrenceService.php
  src/Webhook/Services/SubscriptionHandlerService.php
Labels: :sparkles: Enhancement

#144 Add webhook antifraudreproved
  src/Webhook/Services/ChargeOrderService.php
Labels: :sparkles: Feature

#145 Refactoring recurrence configurations
  src/Kernel/Factories/RecurrenceConfigFactory.php
  src/Kernel/I18N/ENUS.php
  src/Kernel/I18N/PTBR.php
  src/Kernel/ValueObjects/Configuration/RecurrenceConfig.php
  src/Recurrence/Services/CartRules/CompatibleRecurrenceProducts.php
  src/Recurrence/Services/CartRules/CurrentProduct.php
  src/Recurrence/Services/CartRules/MoreThanOneRecurrenceProduct.php
  src/Recurrence/Services/CartRules/NormalWithRecurrenceProduct.php
  src/Recurrence/Services/CartRules/ProductListInCart.php
  src/Recurrence/Services/CartRules/RuleInterface.php
  tests/Recurrence/Aggregates/PlanTest.php
  tests/Recurrence/Aggregates/RepetitionTest.php
  tests/Recurrence/Aggregates/SubscriptionTest.php
  tests/Recurrence/Services/CartRules/CompatibleRecurrenceProductsTest.php
  tests/Recurrence/Services/CartRules/CurrentProductTest.php
  tests/Recurrence/Services/CartRules/MoreThanOneRecurrenceProductTest.php
  tests/Recurrence/Services/CartRules/NormalWithRecurrenceProductTest.php
  tests/Recurrence/Services/CartRules/ProductListInCartTest.php
Labels: :ok_hand: Ready, :sparkles: Feature

#146 Fix discount recurrence
  src/Payment/ValueObjects/Discounts.php
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Services/SubscriptionService.php
Labels: :sparkles: Enhancement, :sparkles: Feature

#147 Fix subscription page columns
  src/Recurrence/Aggregates/Subscription.php
  src/Recurrence/Factories/SubscriptionFactory.php
Labels: :bug: Bug, :ok_hand: Ready

#148 Change webhook status code
  src/Webhook/Exceptions/UnprocessableWebhookException.php
  src/Webhook/Services/ChargeHandlerService.php
  src/Webhook/Services/OrderHandlerService.php
Labels: :bug: Bug, :ok_hand: Ready
