Repository mundipagg/ecommerce-module-core, pull requests merged in 2021-04, with the labels that each got.

#217 Adds pendingReview and analyzing as new valid statuses for transactions
  src/Kernel/ValueObjects/TransactionStatus.php
  tests/Kernel/ValueObjects/TransactionStatusTest.php
Labels: :bug: Bug

#218 Bump version 2.8.4
  composer.json
  src/Maintenance/Assets/integrityData
Labels: :sparkles: Enhancement

#220 Allow transaction status waiting capture
  composer.json
  src/Kernel/ValueObjects/TransactionStatus.php
  src/Maintenance/Assets/integrityData
  tests/Kernel/ValueObjects/TransactionStatusTest.php
Labels: :ambulance: Hotfix
